### ISSUE TITLE
Default parameters not set

### ISSUE THREAD

**Issue by fpolachowski** [psorus/eereid#21]
Add default parameters

```
class ghost():
    def __init__(self,*tags,dataset=None, distance=None, loss=None, model=None, novelty=None, experiments=None,modifier=None,preproc=None,prepros=None,preprocessing=None, **kwargs):
        #add kwargs 
        self.dataset=ee.datasets.mnist()
        self.distance=ee.distances.euclidean()
        self.experiments={}
        self.loss=ee.losses.triplet()
        self.model=ee.models.conv()
        self.modifier=mods()
        self.novelty=None
        self.prepro={}
```

**Comment by psorus** [comment]
I dont get the problem tbh. the standarts are set (but not in the standard way). Like the loss is usually triplet. And if you provide a new loss it gets overwritten. Also I dont find the pull request anymore?

**Comment by psorus** [comment]
ahh the email has more info
basically when you set another loss, the old one gets overwritten always. Same for the other unique variables

**Comment by fpolachowski** [comment]
I saw the overwrite functions at the bottom right after I created this issue. Hence closed it as already resolved.
